const PROTOCOL_CATALOG_COVERAGE = {
  Fragment: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "tracked-out-of-scope",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason:
      "Fragment is a traffic-shaping feature family rather than a wrongsv endpoint protocol.",
  },
  Reality: {
    wrongsv: "implemented",
    wrongcl: "partial",
    external: "covered",
    scenarios: ["vless_reality_vision"],
    configFiles: ["reality-vision.toml"],
    reason: "REALITY is covered as the VLESS REALITY transport profile.",
  },
  GOST: {
    wrongsv: "covered-by-overlap",
    wrongcl: "covered-by-overlap",
    external: "covered",
    scenarios: ["vless_webtransport", "shadowsocks_aead"],
    configFiles: ["webtransport.toml", "shadowsocks-aead.toml"],
    reason: "GOST is an upstream implementation family; wrongsv covers overlapping WebTransport and Shadowsocks protocol shapes.",
  },
  Lua: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "tracked-out-of-scope",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "Lua is configuration scripting, not a proxy wire protocol implemented by wrongsv.",
  },
  "VLESS-Visison": {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vless_tls_vision", "vless_reality_vision"],
    configFiles: ["tls-vision.toml", "reality-vision.toml"],
    reason: "The catalog spelling is preserved; coverage maps to VLESS Vision.",
  },
  VLESS: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: [
      "vless_raw_tcp",
      "vless_tls_tcp",
      "vless_tls_vision",
      "vless_reality_vision",
      "vless_ws_tcp",
      "vless_httpupgrade",
      "vless_grpc",
      "vless_xhttp",
      "vless_meek",
      "vless_gdocsviewer",
      "vless_quic",
      "vless_kcp",
      "vless_webtransport",
    ],
    configFiles: [
      "basic-tcp.toml",
      "tls-tcp.toml",
      "tls-vision.toml",
      "reality-vision.toml",
      "ws-tcp.toml",
      "httpupgrade.toml",
      "grpc.toml",
      "xhttp.toml",
      "meek.toml",
      "gdocsviewer.toml",
      "quic.toml",
      "kcp.toml",
      "webtransport.toml",
    ],
    reason: "VLESS is the base profile for raw, TLS, REALITY, and stream/UDP transports.",
  },
  XHTTP: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vless_xhttp"],
    configFiles: ["xhttp.toml"],
    reason: "XHTTP is covered as a VLESS transport profile.",
  },
  "Shadow-TLS": {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["shadowtls_tcp"],
    configFiles: ["shadowtls.toml"],
    reason: "ShadowTLS is covered as VLESS over ShadowTLS.",
  },
  Snell: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "Snell is not implemented as a wrongsv server or wrongcl client profile.",
  },
  Masque: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "MASQUE is not implemented as a wrongsv endpoint profile.",
  },
  TrustTunnel: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "TrustTunnel is cataloged but not implemented in wrongsv/wrongcl.",
  },
  Brook: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "Brook is cataloged but not implemented in wrongsv/wrongcl.",
  },
  Vlite: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "Vlite is cataloged but not implemented in wrongsv/wrongcl.",
  },
  kcptun: {
    wrongsv: "covered-by-overlap",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vless_kcp"],
    configFiles: ["kcp.toml"],
    reason: "wrongsv covers the KCP/mKCP transport shape used by compatible clients.",
  },
  WireGuard: {
    wrongsv: "implemented",
    wrongcl: "partial",
    external: "covered",
    scenarios: ["wireguard_tunnel_http"],
    configFiles: ["wireguard.toml"],
    reason: "WireGuard tunnel service is covered; imported configs still need the client private key.",
  },
  Tor: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "Tor is a separate anonymity network and not a wrongsv endpoint profile.",
  },
  SSH: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "SSH is used by remote tooling but is not implemented as a proxy protocol in wrongsv.",
  },
  SOCKS: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "local",
    scenarios: [],
    configFiles: ["mixed-proxy.toml"],
    reason: "SOCKS is covered by wrongsv mixed inbound and wrongcl local SOCKS proxy tests.",
  },
  HTTP: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "local",
    scenarios: [],
    configFiles: ["mixed-proxy.toml"],
    reason: "HTTP proxying is covered by wrongsv mixed inbound and wrongcl local HTTP proxy tests.",
  },
  Juicity: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "Juicity is cataloged but not implemented in wrongsv/wrongcl.",
  },
  TUIC: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["tuic_tcp"],
    configFiles: ["tuic.toml"],
    reason: "TUIC v5 is covered by server, wrongcl, and external client scenarios.",
  },
  Mieru: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "Mieru is cataloged but not implemented in wrongsv/wrongcl.",
  },
  Naive: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "harness-gap",
    scenarios: ["naive_tcp"],
    configFiles: ["naive.toml"],
    reason: "Naive is covered by wrongsv and wrongcl; third-party external runtime generation is still a harness gap.",
  },
  Sudoku: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "Sudoku is cataloged but not implemented in wrongsv/wrongcl.",
  },
  "VLESS-Encryption": {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "The newer VLESS encryption variant is tracked separately from current VLESS transport support.",
  },
  ShadowQUIC: {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "ShadowQUIC is cataloged but not implemented in wrongsv/wrongcl.",
  },
  "AnyTLS-Reality": {
    wrongsv: "tracked-out-of-scope",
    wrongcl: "unsupported",
    external: "documented",
    scenarios: [],
    configFiles: [],
    reason: "AnyTLS and REALITY are mutually exclusive wrongsv transport layers.",
  },
  AnyTLS: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["anytls_tcp"],
    configFiles: ["anytls-tcp.toml", "anytls-vision.toml"],
    reason: "AnyTLS is covered as a VLESS outer transport profile.",
  },
  "VLESS-Reality": {
    wrongsv: "implemented",
    wrongcl: "partial",
    external: "covered",
    scenarios: ["vless_reality_vision"],
    configFiles: ["reality-vision.toml", "reality-udp.toml"],
    reason: "VLESS REALITY is covered; wrongcl imports need the public key.",
  },
  "VLESS-XTLS": {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vless_tls_vision", "vless_reality_vision"],
    configFiles: ["tls-vision.toml", "reality-vision.toml", "vision.toml"],
    reason: "XTLS Vision is covered for TCP VLESS flows.",
  },
  Hysteria2: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["hysteria2_tcp"],
    configFiles: ["hysteria2.toml"],
    reason: "Hysteria2 is covered by server, wrongcl, and external client scenarios.",
  },
  "Shadowsocks-2022": {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["shadowsocks_2022"],
    configFiles: ["shadowsocks-2022.toml"],
    reason: "SIP022 AEAD-2022 is covered separately from classic AEAD.",
  },
  Trojan: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["trojan_tls"],
    configFiles: ["trojan-tls.toml"],
    reason: "Trojan over TLS TCP/UDP is covered.",
  },
  Shadowsocks: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["shadowsocks_aead", "shadowsocks_2022"],
    configFiles: ["shadowsocks-aead.toml", "shadowsocks-2022.toml"],
    reason: "Classic Shadowsocks AEAD and AEAD-2022 are both tracked.",
  },
};

const EXTRA_SCENARIO_COVERAGE = {
  vmess_standard: "VMess AEAD is implemented and externally covered, but it is not listed in protocols.md.",
};

function catalogScenarioIds() {
  return new Set(
    Object.values(PROTOCOL_CATALOG_COVERAGE)
      .flatMap((entry) => entry.scenarios || [])
      .concat(Object.keys(EXTRA_SCENARIO_COVERAGE))
  );
}

module.exports = {
  EXTRA_SCENARIO_COVERAGE,
  PROTOCOL_CATALOG_COVERAGE,
  catalogScenarioIds,
};
