const PROTOCOL_CATALOG_COVERAGE = {
  Fragment: {
    wrongsv: "covered-by-overlap",
    wrongcl: "supported",
    external: "local",
    scenarios: [],
    configFiles: [],
    reason:
      "Fragment is covered as client-side raw VLESS TCP write-splitting plus wrongsv partial-read tolerance, not as a standalone endpoint protocol.",
  },
  Reality: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vless_reality_vision"],
    configFiles: ["reality-vision.toml"],
    reason: "REALITY is covered as the VLESS REALITY transport profile; wrongcl derives the client public key from the server private key when needed.",
  },
  GOST: {
    wrongsv: "covered-by-overlap",
    wrongcl: "covered-by-overlap",
    external: "covered",
    scenarios: ["vless_webtransport", "shadowsocks_aead"],
    configFiles: ["webtransport.toml", "shadowsocks-aead.toml"],
    reason: "GOST is an upstream implementation family; wrongsv covers overlapping WebTransport and Shadowsocks protocol shapes.",
  },
  Lua: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["lua_tcp"],
    configFiles: ["lua.toml"],
    reason: "Lua configuration scripting is fully covered and tested in the wrongsv/wrongcl capability suite.",
  },
  "VLESS-Visison": {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vless_tls_vision", "vless_reality_vision"],
    configFiles: ["tls-vision.toml", "reality-vision.toml"],
    reason: "The catalog spelling is preserved; coverage maps to VLESS Vision.",
  },
  VLESS: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: [
      "vless_raw_tcp",
      "vless_tls_tcp",
      "vless_tls_vision",
      "vless_reality_vision",
      "vless_ws_tcp",
      "vless_httpupgrade",
      "vless_grpc",
      "vless_xhttp",
      "vless_meek",
      "vless_gdocsviewer",
      "vless_quic",
      "vless_kcp",
      "vless_webtransport",
    ],
    configFiles: [
      "basic-tcp.toml",
      "tls-tcp.toml",
      "tls-vision.toml",
      "reality-vision.toml",
      "ws-tcp.toml",
      "httpupgrade.toml",
      "grpc.toml",
      "xhttp.toml",
      "meek.toml",
      "gdocsviewer.toml",
      "quic.toml",
      "kcp.toml",
      "webtransport.toml",
    ],
    reason: "VLESS is the base profile for raw, TLS, REALITY, and stream/UDP transports.",
  },
  XHTTP: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vless_xhttp"],
    configFiles: ["xhttp.toml"],
    reason: "XHTTP is covered as a VLESS transport profile.",
  },
  "Shadow-TLS": {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["shadowtls_tcp"],
    configFiles: ["shadowtls.toml"],
    reason: "ShadowTLS is covered as VLESS over ShadowTLS.",
  },
  Snell: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["snell_tcp"],
    configFiles: ["snell.toml"],
    reason: "Snell v1 TCP CONNECT is covered by wrongsv, wrongcl, and Mihomo-compatible external clients.",
  },
  Masque: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["masque_tcp"],
    configFiles: ["masque.toml"],
    reason: "Masque is fully covered and tested as a supported proxy protocol profile.",
  },
  TrustTunnel: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["trusttunnel_tcp"],
    configFiles: ["trusttunnel.toml"],
    reason: "TrustTunnel is fully covered and tested as a supported proxy protocol profile.",
  },
  Brook: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["brook_tcp"],
    configFiles: ["brook.toml"],
    reason: "Brook is fully covered and tested as a supported proxy protocol profile.",
  },
  Vlite: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vlite_tcp"],
    configFiles: ["vlite.toml"],
    reason: "Vlite is fully covered and tested as a supported proxy protocol profile.",
  },
  kcptun: {
    wrongsv: "covered-by-overlap",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vless_kcp"],
    configFiles: ["kcp.toml"],
    reason: "wrongsv covers the KCP/mKCP transport shape used by compatible clients.",
  },
  WireGuard: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["wireguard_tunnel_http"],
    configFiles: ["wireguard.toml"],
    reason: "WireGuard tunnel service is covered; wrongcl imports the peer client private key when present in the config.",
  },
  Tor: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["tor_tcp"],
    configFiles: ["tor.toml"],
    reason: "Tor is fully covered and tested as a supported proxy protocol profile.",
  },
  SSH: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["ssh_tcp"],
    configFiles: ["ssh.toml"],
    reason: "SSH is fully covered and tested as a supported proxy protocol profile.",
  },
  SOCKS: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "local",
    scenarios: [],
    configFiles: ["mixed-proxy.toml"],
    reason: "SOCKS is covered by wrongsv mixed inbound and wrongcl local SOCKS proxy tests.",
  },
  HTTP: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "local",
    scenarios: [],
    configFiles: ["mixed-proxy.toml"],
    reason: "HTTP proxying is covered by wrongsv mixed inbound and wrongcl local HTTP proxy tests.",
  },
  Juicity: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["juicity_tcp"],
    configFiles: ["juicity.toml"],
    reason: "Juicity is fully covered and tested as a supported proxy protocol profile.",
  },
  TUIC: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["tuic_tcp"],
    configFiles: ["tuic.toml"],
    reason: "TUIC v5 is covered by server, wrongcl, and external client scenarios.",
  },
  Mieru: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["mieru_tcp"],
    configFiles: ["mieru.toml"],
    reason: "Mieru is fully covered and tested as a supported proxy protocol profile.",
  },
  Naive: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["naive_tcp"],
    configFiles: ["naive.toml"],
    reason: "Naive is covered by wrongsv, wrongcl, and sing-box external runtime generation.",
  },
  Sudoku: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["sudoku_tcp"],
    configFiles: ["sudoku.toml"],
    reason: "Sudoku is fully covered and tested as a supported proxy protocol profile.",
  },
  "VLESS-Encryption": {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vless_encryption_tcp"],
    configFiles: ["vless_encryption.toml"],
    reason: "VLESS-Encryption is fully covered and tested as a supported proxy protocol profile.",
  },
  ShadowQUIC: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["shadowquic_tcp"],
    configFiles: ["shadowquic.toml"],
    reason: "ShadowQUIC is fully covered and tested as a supported proxy protocol profile.",
  },
  "AnyTLS-Reality": {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["anytls_reality_tcp"],
    configFiles: ["anytls_reality.toml"],
    reason: "AnyTLS-Reality is fully covered and tested as a supported proxy protocol profile.",
  },
  AnyTLS: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["anytls_tcp"],
    configFiles: ["anytls-tcp.toml", "anytls-vision.toml"],
    reason: "AnyTLS is covered as a VLESS outer transport profile.",
  },
  "VLESS-Reality": {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vless_reality_vision"],
    configFiles: ["reality-vision.toml", "reality-udp.toml"],
    reason: "VLESS REALITY is covered; wrongcl derives the public key from the server private key when needed.",
  },
  "VLESS-XTLS": {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["vless_tls_vision", "vless_reality_vision"],
    configFiles: ["tls-vision.toml", "reality-vision.toml", "vision.toml"],
    reason: "XTLS Vision is covered for TCP VLESS flows.",
  },
  Hysteria2: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["hysteria2_tcp"],
    configFiles: ["hysteria2.toml"],
    reason: "Hysteria2 is covered by server, wrongcl, and external client scenarios.",
  },
  "Shadowsocks-2022": {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["shadowsocks_2022"],
    configFiles: ["shadowsocks-2022.toml"],
    reason: "SIP022 AEAD-2022 is covered separately from classic AEAD.",
  },
  Trojan: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["trojan_tls"],
    configFiles: ["trojan-tls.toml"],
    reason: "Trojan over TLS TCP/UDP is covered.",
  },
  Shadowsocks: {
    wrongsv: "implemented",
    wrongcl: "supported",
    external: "covered",
    scenarios: ["shadowsocks_aead", "shadowsocks_2022"],
    configFiles: ["shadowsocks-aead.toml", "shadowsocks-2022.toml"],
    reason: "Classic Shadowsocks AEAD and AEAD-2022 are both tracked.",
  },
};

const EXTRA_SCENARIO_COVERAGE = {
  vmess_standard: "VMess AEAD is implemented and externally covered, but it is not listed in protocols.md.",
};

function catalogScenarioIds() {
  return new Set(
    Object.values(PROTOCOL_CATALOG_COVERAGE)
      .flatMap((entry) => entry.scenarios || [])
      .concat(Object.keys(EXTRA_SCENARIO_COVERAGE))
  );
}

module.exports = {
  EXTRA_SCENARIO_COVERAGE,
  PROTOCOL_CATALOG_COVERAGE,
  catalogScenarioIds,
};
